services:
  web:
    build: .
    container_name: docker-ci-sample
    ports:
      - "54010:54010"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:54010/health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s