services:
  web:
    build: .
    container_name: docker-ci-sample
    ports:
      - "55010:8000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000/health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s