name: CI (Docker + Compose)

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch: {}

jobs:
  build-and-smoke-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        run: docker build -t docker-ci-sample:${{ github.sha }} .

      - name: Start with Docker Compose
        run: docker compose up -d

      - name: Wait for service
        run: |
          for i in {1..20}; do
            if curl -fsS http://localhost:54010/health; then exit 0; fi
            echo "Waiting for app... ($i)" && sleep 2
          done
          exit 1

      - name: Smoke test root endpoint
        run: curl -fsS http://localhost:54010/ | jq .

      - name: Tear down
        if: always()
        run: docker compose down -v