name: Deploy on Server (Self-Hosted)
env:
  MY_TEST_SECRET: ${{ secrets.API_KEY }}
on:
  push:
    branches: ["main"]   # change if you deploy from another branch
  workflow_dispatch: {}

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build & (re)start with Docker Compose
        run: |
          docker compose pull || true
          docker compose up -d --build

      - name: Health check
        run: |
          for i in {1..15}; do
            if curl -fsS http://localhost:54020/health > /dev/null; then
              echo "Healthy"; exit 0; fi
            echo "Waiting for app... ($i)"; sleep 2
          done
          echo "Health check failed"; docker compose logs --no-color; exit 1